#pragma once
#define FSM_SIGNAL_ERROR                        0
#define FSM_SIGNAL_USER_CONFIRMATION            1
#define FSM_SIGNAL_EARBUDS_RESET_DONE           2
#define FSM_SIGNAL_FIRST_PAIRING_DONE           3
#define FSM_SIGNAL_EARBUDS_ARE_IN_CASE_FIRST    4
#define FSM_SIGNAL_EARBUDS_ARE_OUT_OF_CASE      5
#define FSM_SIGNAL_SECOND_PAIRING_DONE          6
#define FSM_SIGNAL_EARBUDS_ARE_IN_CASE_SECOND   7
#define FSM_SIGNAL_WRONG_PRIMARY_DEVICE_ROLE    8
#define FSM_SIGNAL_PRIMARY_DEVICE_REQ_FAILED    9
#define FSM_SIGNAL_PAIRING_TIMEOUT              10




