#include "Languages.hpp"
#include "TitlesTypes.hpp"

using namespace Languages;

static const char* russianGlossaryData[static_cast<int>(eTitleType::TITLE_MAX)] {
    "Батарея разряжена!",
    "Переход в спящий режим",
    "Выключение",
    "Обновление завершено.\nВыключение",
    "Теперь можно отпустить кнопку",
    "Пожалуйста, подождите",
    "Обновление может занять 3-5 минут.\nПожалуйста, подождите",
    "ЛЕВЫЙ",
    "ПРАВЫЙ",
    "Кейс",
    "Громкость",
    "Прозрачность",
    "Микрофон",
    "Шумоподавление",
    "Энергосбережение через",
    "сек",
    "Блокировка экрана",
    "Разблокируйте экран",
    "Поиск наушников...",
    "Подключение к наушникам...",
    "Ошибка запроса",
    "Превышено время ожидания",
    "Успешно",
    "Ошибка",
    "Режим сопряжения активирован",
    "Сначала отключите устройство",
    "Команда отправлена",
    "Отключение...",
    "Наушники подключены",
    "Точка доступа запущена. Пароль для подключения: 12345678",
    "Вебсервер доступен по адресу 192.168.4.1",
    "Вебсеревр остановлен",
    "Ошибка обновления",
    "Отмена",
    "ОК",
    "Далее",
    "Будет выполнен сброс к заводским настройкам. Хотите продолжить?",
    "Выполните сброс к заводским настройкам для наушников и нажмите \"Далее\"",
    "Сопряжение с наушниками\nПожалуйста, подождите",
    "Поместите в кейс #ffff00 %s# наушник, затем #ffff00 %s# наушник",
    "Достаньте #ffff00 %s# наушник из кейса, а затем #ffff00 %s# наушник. Включите режим сопряжения на наушниках",
    "Ошибка: не удалось определить главный наушник",
    "Ошибка: ожидалось, что #ffff00 %s# наушник не будет главным",
    "Ошибка: не удалось запросить информацию о главном наушнике",
    "Ошибка: превышено время ожидания сопряжения",
    "Сброс к заводским настройкам произведен",
    "Ошибка: что-то пошло не так",
    "Максимум 8 устройств, сначала удалите устройство"
};

static const char* englishGlossaryData[static_cast<int>(eTitleType::TITLE_MAX)] {
    "Low battery",
    "Entering power saving",
    "Switching off",
    "Firmware updated successfully!\nSwitching off",
    "Please, release the button",
    "Please, wait",
    "Firmware updating.\nIt can take 3-5 minutes",
    "LEFT",
    "RIGHT",
    "case battery",
    "Volume",
    "Transparency",
    "Mic",
    "ANC",
    "Power saving after",
    "sec",
    "Screen lock",
    "Slide to unlock",
    "Searching for earbuds",
    "Connecting to earbuds",
    "Request failed",
    "Timeout",
    "Success",
    "Failed",
    "Pairing mode activated",
    "Disconnect device before deleting",
    "Command sent",
    "Disconnecting",
    "Earbuds connected",
    "WiFi access point launched with password 12345678",
    "Webserver started at: 192.168.4.1",
    "Webserver stopped",
    "Firmware update failed",
    "Cancel",
    "OK",
    "Next",
    "Factory reset will be performed.\nDo you want to continue?",
    "Please, perform factory reset for earbuds and press \"Next\"",
    "Pairing with earbuds.\nPlease, wait",
    "Please, put #ffff00 %s# earbud in case, followed by #ffff00 %s# earbud",
    "Please, take #ffff00 %s# earbud from case, followed by #ffff00 %s# earbud. Set earbuds into pairing mode",
    "Error: failed to detect which earbud is primary",
    "Error: #ffff00 %s# earbud was not expected to be primary",
    "Error: failed to request primary earbud role",
    "Error: pairing timeout",
    "Factory reset completed",
    "Error: something went wrong",
    "Max of 8 devices, delete a device before adding a new one"
};

static const char* italianGlossaryData[static_cast<int>(eTitleType::TITLE_MAX)] {
    "Batteria livello basso",
    "Modalità risparmio energetico",
    "Spegnimento",
    "Aggiornamento firmware riuscito!\nSpegnimento",
    "Rilasciare il pulsante, prego",
    "Attendere, prego",
    "Aggiornamento firmware.\nPuò durare 3-5 minuti",
    "Sinistra",
    "Destra",
    "Custodia batteria",
    "Volume",
    "Trasparenza",
    "Mic",
    "ANC",
    "Risparmio energetico dopo",
    "sec",
    "Blocco schermo",
    "Scorrere per sbloccare",
    "Ricerca auricolari",
    "Collegamento auricolari",
    "Richiesta fallita",
    "Tempo scaduto",
    "Successo",
    "Fallito",
    "Modalità abbinamento attivata",
    "Disconnettere dispositivo prima di eliminare",
    "Commando inviato",
    "Disconnessione",
    "Auricolari connessi",
    "Password accesso WiFi 12345678",
    "Server Web avviato da: 192.168.4.1",
    "Server Web interrotto",
    "Aggiornamento firmware fallito",
    "Cancellare",
    "OK",
    "Avanti", 
    "Verrà eseguito ripristino impostazioni di fabbrica. Vuoi continuare?",
    "Eseguire ripristino impostazioni di fabbrica per auricolari e premere Avanti",
    "Abbinamento con auricolari… Attendere, prego",
    "Mettere auricolare #ffff00 %s# nella custodia, seguito dall’auricolare #ffff00 %s#",
    "Prendere auricolare #ffff00 %s# dalla custodia, seguito dall’auricolare #ffff00 %s#. Imposta auricolari in modalità abbinamento",
    "Errore: fallito rilevamento auricolare principale",
    "Errore: non era previsto auricolare #ffff00 %s# come principale",
    "Errore: fallita richiesta ruolo auricolare principale",
    "Errore: tempo di abbinamento scaduto",
    "Ripristino impostazioni di fabbrica completato",
    "Errore: qualcosa non ha funzionato",
    "Massimo 8 dispositivi, elimina un dispositivo prima di aggiungerne uno nuovo"
};

static const char* germanGlossaryData[static_cast<int>(eTitleType::TITLE_MAX)] {
    "Entladene Batterie",
    "Stromsparmodus",
    "Ausschaltung",
    "Firmware erfolgreich aktualisiert!\nAusschaltung",
    "Bitte lassen Sie den Knopf los",
    "Bitte warten Sie",
    "Firmware aktualisiert.\nEs kann 3-5 Minuten dauern",
    "LINKEN", 
    "RECHTEN", 
    "Batteriefach",
    "Volume",
    "Transparenz",
    "Mikro",
    "Antischallsystem",
    "Stromsparmodus nach",
    "sek",
    "Bildschirmsperre",
    "Schieben zum Entsperren",
    "Suche nach Ohrhörern",
    "Verbindung mit den Ohrhörern",
    "Anfrage fehlgeschlagen",
    "Wartezeit",
    "Erfolg",
    "Erfolglos",
    "Anschlussmodus aktiviert",
    "Trennen Sie Gerät vor dem Löschen",
    "Befehl gesendet",
    "Unterbrechung",
    "Ohrhörer angeschlossen",
    "WiFi-Zugangspunkt mit Passwort 12345678 starten",
    "Webserver unter: 192.168.4.1 gestartet",
    "Webserver gestoppt",
    "Firmwareaktualisierung fehlgeschlagen",
    "Abbrechen",
    "OK",
    "Weiter",
    "Zurücksetzen auf Werkseinstellungen wird durchgeführt. Möchten Sie fortsetzen?",
    "Bitte setzen Sie auf Werkseinstellungen für Ohrhörer zurück und drücken Sie Weiter",
    "Anschluss an Ohrhörer...Bitte warten Sie",
    "Bitte legen Sie den #ffff00 %s# Ohrhörer in Hülle und dann den #ffff00 %s# Ohrhörer.",
    "Bitte nehmen Sie den #ffff00 %s# Ohrhörer aus Hülle und dann den #ffff00 %s# Ohrhörer. Setzen Ohrhörer in den Anschlussmodus...",
    "Fehler: Man konnte nicht erkennen, welcher Ohrhörer primär ist",
    "Fehler: #ffff00 %s# Ohrhörer soll nicht als primär sein",
    "Fehler: Man konnte nicht primären Ohrhörer anfordern",
    "Fehler: Wartezeit des Anschlusses",
    "Zurücksetzen auf Werkseinstellungen abgeschlossen",
    "Fehler: Etwas ist schiefgegangen",
    "Max. 8 Geräte, löschen Sie ein Gerät, bevor Sie ein neues hinzufügen"
};

static const char* japaneseGlossaryData[static_cast<int>(eTitleType::TITLE_MAX)] {
    "バッテリー残量が少なくなった",
    "節電モードに入る",
    "スイッチを切る",
    "ファームウェアの更新に成功した！\nスイッチを切る",
    "ボタンを離してください",
    "お待ちください",
    "ファームウェアが更新されている.\n3〜5分かかる場合がある",
    "左",
    "右",
    "ケースバッテリー",
    "音量",
    "透明性",
    "マイク",
    "消音スピーカー",
    "節電モードは後",
    "秒",
    "スクリーンロック",
    "スライドしてロック解除する",
    "イヤフォンを探している",
    "イヤフォンに接続している",
    "要求が失敗した",
    "タイムアウト",
    "成功",
    "失敗した",
    "ペアリングモードがアクティブになった",
    "削除する前にデバイスを切断する",
    "コマンドが送信された",
    "切断している",
    "イヤフォンが接続された",
    "WiFiアクセスポイントがパスワード12345678で起動された",
    "Webサーバーの開始場所：192.168.4.1",
    "Webサーバーが停止した",
    "ファームウェアの更新が失敗した",
    "キャンセル",
    "オーケー",
    "次へ",
    "工場出荷時のリセットが実行されます。 続けますか？",
    "イヤフォンの工場出荷時のリセットを実行して、[次へ]を押してください",
    "イヤフォンとのペアリング...お待ちください",
    "ケースに#ffff00 %s#イヤフォンを入れ、次に#ffff00 %s#イヤフォンを入れてください",
    "ケースから#ffff00 %s#のイヤフォンを取り出し、次に#ffff00 %s#のイヤフォンを取り出してください。 イヤフォンをペアリングモードに設定する",
    "エラー：どのイヤフォンがプライマリであるかを検出できなかった",
    "エラー：#ffff00 %s#のイヤフォンがプライマリであるとは予想されていなかった",
    "エラー：プライマリイヤフォンの役割をリクエストできなかった",
    "エラー：ペアリングタイムアウト",
    "工場出荷時のリセットが完了した",
    "エラー：問題が発生した",
    "8台のデバイスの限制に達しました。新しいデバイスを追加する前に、デバイスを削除してください。"
};

const char** Languages::russianGlossary() {
    return russianGlossaryData;
}

const char** Languages::englishGlossary() {
    return englishGlossaryData;
}

const char** Languages::italianGlossary() {
    return italianGlossaryData;
}

const char** Languages::germanGlossary() {
    return germanGlossaryData;
}

const char** Languages::japaneseGlossary() {
    return japaneseGlossaryData;
}