#pragma once
#include "stdint.h"

namespace Languages {

    enum class eTitleType {
        TITLE_BATTERY_EMPTY = 0,            // "Low battery!" - is shown on startup with discharged battery
        TITLE_GOING_TO_POWER_SAVING,        // 
        TITLE_SWITCHING_OFF,
        TITLE_OTA_COMPLETED,
        TITLE_RELEASE_BUTTON,
        TITLE_PLEASE_WAIT,
        TITLE_OTA_WAIT,
        TITLE_LEFT,
        TITLE_RIGHT,
        TITLE_CASE_BATTERY,
        TITLE_VOLUME,
        TITLE_TRANSPARENCY,
        TITLE_MIC,
        TITLE_ANC,
        TITLE_POWER_SAVING_AFTER,
        TITLE_SEC,
        TITLE_UNLOCK,
        TITLE_SWIPE_TO_UNLOCK,
        TITLE_EARBUDS_SEARCHING,
        TITLE_EARBUDS_CONNECTION,
        TITLE_REQUEST_FAILED,
        TITLE_TIMEOUT,
        TITLE_SUCCESS,
        TITLE_FAILED,
        TITLE_PAIRING_MODE_ACTIVATED,
        TITLE_DISCONNECT_FIRST,
        TITLE_COMMAND_SENT,
        TITLE_DISCONNECTING,
        TITLE_EARBUDS_CONNECTED,
        TITLE_WIFI_LAUNCHED,
        TITLE_WEBSERVER_LAUNCHED,
        TITLE_WEBSERVER_STOPPED,
        TITLE_OTA_FAILED,
        TITLE_RESET_CANCEL,
        TITLE_RESET_OK,
        TITLE_RESET_NEXT,
        TITLE_RESET_PRESS_NEXT,
        TITLE_RESET_EARBUDS_RESET,
        TITLE_RESET_WAIT_FOR_CONNECTION,
        TITLE_RESET_PUT_EARBUDS,
        TITLE_RESET_TAKE_EARBUDS,
        TITLE_RESET_FAILED_GET_PRIMARY,
        TTITLE_RESET_NOT_EXPECTED_PRIMARY,
        TTITLE_RESET_FAILED_REQUEST_PRIMARY,
        TITLE_RESET_PAIRING_TIMEOUT,
        TITLE_RESET_COMPLETED,
        TITLE_RESET_SMTH_WRONG,
        TITLE_MAX_DEVICES,
        TITLE_MAX
    };
};