#pragma once
#include <stdint.h>

enum class eMorphCommands : uint8_t {
    MORPH_COMMAND_ID_VERSION = 0x00,
    MORPH_COMMAND_ID_GET_VOLUME = 0x01,
    MORPH_COMMAND_ID_CHANGE_VOLUME = 0x02,
    MORPH_COMMAND_ID_TOGGLE_MIC_MUTE_STATE = 0x03,
    MORPH_COMMAND_ID_GET_MIC_MUTE_STATE = 0x04,
    MORPH_COMMAND_ID_PAIR_HANDSET = 0x05,
    MORPH_COMMAND_ID_IS_HANDSET_CONNECTED = 0x06,
    MORPH_COMMAND_ID_GET_HANDSET_CONNECTED = 0x07,
    MORPH_COMMAND_ID_GET_BATTERY_LEVEL = 0x08,
    MORPH_COMMAND_ID_CONNECT_PREV_HANDSET = 0x09,
    MORPH_COMMAND_ID_CONNECT_DISCONNECT_ALL = 0x0A,
    MORPH_COMMAND_ID_DISCONNECT_PREV = 0x0B,
    MORPH_COMMAND_ID_DELETE_PAIRED_HANDSET = 0x0C,
    MORPH_COMMAND_PLAY_TONE = 0x0E,
    MORPH_COMMAND_ID_REQUEST_NUM_PAIRED_HANDSETS = 0x12,
    MORPH_COMMAND_ID_REQUEST_PAIRED_HANDSETS = 0x13,
    MORPH_COMMAND_ID_MAX,
};