#pragma once

#include "LVGLButton.hpp"
#include "LVGLNumberBox.hpp"
#include "LVGLRow.hpp"
#include "LVGLColumn.hpp"
#include "LVGLLabel.hpp"
#include "LVGLTabView.hpp"
#include "LVGLSwitch.hpp"
#include "LVGLSlider.hpp"
#include "LVGLUnlocker.hpp"
#include "LVGLArc.hpp"
#include "LVGLBatteryIndicator.hpp"
#include "LVGLImage.hpp"
#include "LVGLSpinner.hpp"
#include "LVGLToaster.hpp"
